### ISSUE TITLE
Unable to import modules

### ISSUE THREAD

**Issue by caioboffo** [evedovelli/climatic#3]
Steps to reproduce:

- pip install climatic 
- create sample file as: 
```
import climatic

a = climatic.connetions.Ssh("192.168.1.15", "admin") 
```
- This gives me: AttributeError: module 'climatic' has no attribute 'connections'

**Comment by evedovelli** [comment]
Hi @caioboffo, thanks for you interest in using Climatic.

Climatic is only supported in Python3. Certify that pip is calling the pip3 executable, or run `pip3 install climatic`.

Also, the way to use it is not as from your example. For using it with a SSH connection to a Linux Shell, please follow the documentations here: https://github.com/evedovelli/climatic#usage . The usage documentation also explains how to use it with a client library, and gives as example the usage with python3 CLI, which requires the installation of https://github.com/evedovelli/climatic-python

For other CLIs, the specific client library should be implemented, taking as example the https://github.com/evedovelli/climatic-python or https://github.com/evedovelli/climatic-ipinfusion (for OcNOS CLI, similar to Cisco's CLI).
